server:
  port: 9999

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Users/jason/local/github/service-keeper.db
    username:
    password:
service-keeper:
  deployment-log-path: /Users/jason/local/logs/service-keeper/

