server:
  port: 9999

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:\\service-keeper-db\\service-keeper.db
    username:
    password:


service-keeper:
